url: "http://www.kairaleekalanilayam.com/"
baseurl: "/"

# Site settings
title: Singapore Kairalee Kala Nilayam
email: singaporekairaleekalanilayam@gmail.com
description: "Singapore Kairalee Kala Nilayam, Welcome To The Pioneer INDIAN ART HOUSE of Singapore"

favicon: 'assets/images/favicon.ico'

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/sgkairalee
  - title: facebook
    url: https://www.facebook.com/KairaleeKalaNilayam

# Postal address (add as many lines as necessary)
address:
  - line: 110 Faber Terrace
  - line: Singapore, 129065

# Build settings
markdown: kramdown
permalink: pretty
